#
###################################
# Site wide configuration
####################################
#
title: Jaken Herman
email: JakenHerman7@Gmail.com
description: Software Engineer, Brewer of Beer, Husband
url: www.jakenherman.com
keywords: ["blog", "jaken", "herman", "software", "engineer"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: jaken herman
  avatar: avatar.jpg
  job: "Software Engineer"
  bio: "I'm a full-stack software engineer specializing in the ASP.NET framework in both Visual Basic and C#. 
        I also work on Mobile Application development using both the Xamarin.Forms framework and Apache Cordova framework depending on the project.
        I'm well-versed in JavaScript and many of it's popular libraries and frameworks."
  email: jakenherman7@gmail.com
  disqus-shortname:
  twitter: 0x6a6368h
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JakenHerman
  gitlab: #username
  stackoverflow: 2752265/jaken-herman?tab=profile
  linkedin: jakenherman
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username