#
###################################
# Site wide configuration
####################################
#
title: Carlton Whitmore
email: cwhitmore88@gmail.com
description: IT Manager, Father, Husband, Coach
url:
keywords: ["blog", "carlton", "whitmore", "aws", "azure"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: carlton whitmore
  avatar: Headshotreduced.jpg
  job: "IT Manager for non-profit"
  bio: "husband | father | coach"
  email: cwhitmore88@gmail.com
  disqus-shortname: https-carltonw-github-io
  twitter: 0x6a6368h
  # amazon-author: amazon.com/author/jakenherman
  # facebook: #username
  google:
    plus: #username
    analytics: UA-134666359-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JakenHerman
  # gitlab: #username
  # stackoverflow: 2752265/jaken-herman?tab=profile
  linkedin: jakenherman
  # skype: jaken2711
  xing: #username
  # instagram: jaken.herman
  lastfm: #username
  # tumblr: #username
  # pinterest: #username
  # foursquare: #username
  # steam: #username
  # dribbble: jakenherman
  youtube: jakencherman
  # soundcloud: #username
  # weibo: #username
  # flickr: #username
  # 500px: #username
  # codepen: JakenHerman
  # reddit: #username
  # telegram: #username
  # tripadvisor : jakenherman
  # strava: jaken_herman
