#
###################################
# Site wide configuration
####################################
#
title: Carlton Whitmore
email: cwhitmore88@gmail.com
description: Husband, Father, Tech guy, Runner
url:
keywords: ["blog", "carlton", "whitmore", "aws", "azure", "WSL", "WSL2"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: carlton whitmore
  avatar: Picture3.jpg
  job: "Information Technology Manager for non-profit"
  bio: "husband | father | runner"
  email: cwhitmore88@gmail.com
  disqus-shortname: https-carltonw-github-io
  twitter: WhitmoreCarlton
  # amazon-author: amazon.com/author/jakenherman
  # facebook: #username
  google:
    plus: #username
    analytics: UA-147639042-1
    # google_site_verification: sIujgX6GvM_IJHu_2yr7iNP-2qGwbWk_ST107zMgJ4U
    verify: 
    ad-client:
    ad-slot:
  bing-verify:
  github: CarltonW
  # gitlab: #username
  # stackoverflow: 2752265/jaken-herman?tab=profile
  linkedin: carlton-whitmore-060840
  # skype: jaken2711
  # xing: #username
  # instagram: jaken.herman
  # lastfm: #username
  # tumblr: #username
  # pinterest: #username
  # foursquare: #username
  # steam: #username
  # dribbble: jakenherman
  youtube: ITComputeGuru
  # soundcloud: #username
  # weibo: #username
  # flickr: #username
  # 500px: #username
  # codepen: JakenHerman
  # reddit: #username
  # telegram: #username
  # tripadvisor : jakenherman
  # strava: jaken_herman
